using Demo.Library.Extensions;
using NServiceBus;
using Seed.Attributes;
using Seed.Internal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Commands = Demo.Domain.Configuration.Country.Commands;
using Type = Seed.Types.Configuration;

namespace Seed.Operations
{
    [Operation("Country")]
    [Category("Configuration")]
    public class Country : IOperation
    {
        public static IEnumerable<Type.Country> Data = new[] {
            new Type.Country { Id = Guid.NewGuid(), Code = "AF", Name = "Afghanistan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AX", Name = "Åland Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AL", Name = "Albania" },
            new Type.Country { Id = Guid.NewGuid(), Code = "DZ", Name = "Algeria" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AS", Name = "American Samoa" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AD", Name = "Andorra" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AO", Name = "Angola" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AI", Name = "Anguilla" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AQ", Name = "Antarctica" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AG", Name = "Antigua and Barbuda" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AR", Name = "Argentina" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AM", Name = "Armenia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AW", Name = "Aruba" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AU", Name = "Australia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AT", Name = "Austria" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AZ", Name = "Azerbaijan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BS", Name = "Bahamas" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BH", Name = "Bahrain" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BD", Name = "Bangladesh" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BB", Name = "Barbados" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BY", Name = "Belarus" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BE", Name = "Belgium" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BZ", Name = "Belize" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BJ", Name = "Benin" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BM", Name = "Bermuda" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BT", Name = "Bhutan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BO", Name = "Bolivia, Plurinational State of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BQ", Name = "Bonaire, Sint Eustatius and Saba" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BA", Name = "Bosnia and Herzegovina" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BW", Name = "Botswana" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BV", Name = "Bouvet Island" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BR", Name = "Brazil" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IO", Name = "British Indian Ocean Territory" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BN", Name = "Brunei Darussalam" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BG", Name = "Bulgaria" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BF", Name = "Burkina Faso" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BI", Name = "Burundi" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KH", Name = "Cambodia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CM", Name = "Cameroon" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CA", Name = "Canada" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CV", Name = "Cape Verde" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KY", Name = "Cayman Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CF", Name = "Central African Republic" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TD", Name = "Chad" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CL", Name = "Chile" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CN", Name = "China" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CX", Name = "Christmas Island" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CC", Name = "Cocos(Keeling) Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CO", Name = "Colombia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KM", Name = "Comoros" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CG", Name = "Congo" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CD", Name = "Congo, the Democratic Republic of the" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CK", Name = "Cook Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CR", Name = "Costa Rica" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CI", Name = "Côte d'Ivoire" },
            new Type.Country { Id = Guid.NewGuid(), Code = "HR", Name = "Croatia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CU", Name = "Cuba" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CW", Name = "Curaçao" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CY", Name = "Cyprus" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CZ", Name = "Czech Republic" },
            new Type.Country { Id = Guid.NewGuid(), Code = "DK", Name = "Denmark" },
            new Type.Country { Id = Guid.NewGuid(), Code = "DJ", Name = "Djibouti" },
            new Type.Country { Id = Guid.NewGuid(), Code = "DM", Name = "Dominica" },
            new Type.Country { Id = Guid.NewGuid(), Code = "DO", Name = "Dominican Republic" },
            new Type.Country { Id = Guid.NewGuid(), Code = "EC", Name = "Ecuador" },
            new Type.Country { Id = Guid.NewGuid(), Code = "EG", Name = "Egypt" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SV", Name = "El Salvador" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GQ", Name = "Equatorial Guinea" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ER", Name = "Eritrea" },
            new Type.Country { Id = Guid.NewGuid(), Code = "EE", Name = "Estonia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ET", Name = "Ethiopia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "FK", Name = "Falkland Islands(Malvinas)" },
            new Type.Country { Id = Guid.NewGuid(), Code = "FO", Name = "Faroe Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "FJ", Name = "Fiji" },
            new Type.Country { Id = Guid.NewGuid(), Code = "FI", Name = "Finland" },
            new Type.Country { Id = Guid.NewGuid(), Code = "FR", Name = "France" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GF", Name = "French Guiana" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PF", Name = "French Polynesia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TF", Name = "French Southern Territories" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GA", Name = "Gabon" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GM", Name = "Gambia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GE", Name = "Georgia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "DE", Name = "Germany" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GH", Name = "Ghana" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GI", Name = "Gibraltar" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GR", Name = "Greece" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GL", Name = "Greenland" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GD", Name = "Grenada" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GP", Name = "Guadeloupe" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GU", Name = "Guam" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GT", Name = "Guatemala" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GG", Name = "Guernsey" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GN", Name = "Guinea" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GW", Name = "Guinea - Bissau" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GY", Name = "Guyana" },
            new Type.Country { Id = Guid.NewGuid(), Code = "HT", Name = "Haiti" },
            new Type.Country { Id = Guid.NewGuid(), Code = "HM", Name = "Heard Island and McDonald Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "VA", Name = "Holy See(Vatican City State)" },
            new Type.Country { Id = Guid.NewGuid(), Code = "HN", Name = "Honduras" },
            new Type.Country { Id = Guid.NewGuid(), Code = "HK", Name = "Hong Kong" },
            new Type.Country { Id = Guid.NewGuid(), Code = "HU", Name = "Hungary" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IS", Name = "Iceland" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IN", Name = "India" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ID", Name = "Indonesia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IR", Name = "Iran, Islamic Republic of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IQ", Name = "Iraq" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IE", Name = "Ireland" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IM", Name = "Isle of Man" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IL", Name = "Israel" },
            new Type.Country { Id = Guid.NewGuid(), Code = "IT", Name = "Italy" },
            new Type.Country { Id = Guid.NewGuid(), Code = "JM", Name = "Jamaica" },
            new Type.Country { Id = Guid.NewGuid(), Code = "JP", Name = "Japan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "JE", Name = "Jersey" },
            new Type.Country { Id = Guid.NewGuid(), Code = "JO", Name = "Jordan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KZ", Name = "Kazakhstan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KE", Name = "Kenya" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KI", Name = "Kiribati" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KP", Name = "Korea, Democratic People's Republic of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KR", Name = "Korea, Republic of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KW", Name = "Kuwait" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KG", Name = "Kyrgyzstan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LA", Name = "Lao People's Democratic Republic" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LV", Name = "Latvia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LB", Name = "Lebanon" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LS", Name = "Lesotho" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LR", Name = "Liberia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LY", Name = "Libya" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LI", Name = "Liechtenstein" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LT", Name = "Lithuania" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LU", Name = "Luxembourg" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MO", Name = "Macao" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MK", Name = "Macedonia, the former Yugoslav Republic of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MG", Name = "Madagascar" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MW", Name = "Malawi" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MY", Name = "Malaysia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MV", Name = "Maldives" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ML", Name = "Mali" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MT", Name = "Malta" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MH", Name = "Marshall Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MQ", Name = "Martinique" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MR", Name = "Mauritania" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MU", Name = "Mauritius" },
            new Type.Country { Id = Guid.NewGuid(), Code = "YT", Name = "Mayotte" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MX", Name = "Mexico" },
            new Type.Country { Id = Guid.NewGuid(), Code = "FM", Name = "Micronesia, Federated States of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MD", Name = "Moldova, Republic of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MC", Name = "Monaco" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MN", Name = "Mongolia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ME", Name = "Montenegro" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MS", Name = "Montserrat" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MA", Name = "Morocco" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MZ", Name = "Mozambique" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MM", Name = "Myanmar" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NA", Name = "Namibia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NR", Name = "Nauru" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NP", Name = "Nepal" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NL", Name = "Netherlands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NC", Name = "New Caledonia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NZ", Name = "New Zealand" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NI", Name = "Nicaragua" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NE", Name = "Niger" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NG", Name = "Nigeria" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NU", Name = "Niue" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NF", Name = "Norfolk Island" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MP", Name = "Northern Mariana Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "NO", Name = "Norway" },
            new Type.Country { Id = Guid.NewGuid(), Code = "OM", Name = "Oman" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PK", Name = "Pakistan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PW", Name = "Palau" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PS", Name = "Palestinian Territory, Occupied" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PA", Name = "Panama" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PG", Name = "Papua New Guinea" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PY", Name = "Paraguay" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PE", Name = "Peru" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PH", Name = "Philippines" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PN", Name = "Pitcairn" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PL", Name = "Poland" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PT", Name = "Portugal" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PR", Name = "Puerto Rico" },
            new Type.Country { Id = Guid.NewGuid(), Code = "QA", Name = "Qatar" },
            new Type.Country { Id = Guid.NewGuid(), Code = "RE", Name = "Réunion" },
            new Type.Country { Id = Guid.NewGuid(), Code = "RO", Name = "Romania" },
            new Type.Country { Id = Guid.NewGuid(), Code = "RU", Name = "Russian Federation" },
            new Type.Country { Id = Guid.NewGuid(), Code = "RW", Name = "Rwanda" },
            new Type.Country { Id = Guid.NewGuid(), Code = "BL", Name = "Saint Barthélemy" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SH", Name = "Saint Helena, Ascension and Tristan da Cunha" },
            new Type.Country { Id = Guid.NewGuid(), Code = "KN", Name = "Saint Kitts and Nevis" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LC", Name = "Saint Lucia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "MF", Name = "Saint Martin(French part)" },
            new Type.Country { Id = Guid.NewGuid(), Code = "PM", Name = "Saint Pierre and Miquelon" },
            new Type.Country { Id = Guid.NewGuid(), Code = "VC", Name = "Saint Vincent and the Grenadines" },
            new Type.Country { Id = Guid.NewGuid(), Code = "WS", Name = "Samoa" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SM", Name = "San Marino" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ST", Name = "Sao Tome and Principe" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SA", Name = "Saudi Arabia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SN", Name = "Senegal" },
            new Type.Country { Id = Guid.NewGuid(), Code = "RS", Name = "Serbia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SC", Name = "Seychelles" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SL", Name = "Sierra Leone" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SG", Name = "Singapore" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SX", Name = "Sint Maarten(Dutch part)" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SK", Name = "Slovakia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SI", Name = "Slovenia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SB", Name = "Solomon Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SO", Name = "Somalia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ZA", Name = "South Africa" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GS", Name = "South Georgia and the South Sandwich Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SS", Name = "South Sudan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ES", Name = "Spain" },
            new Type.Country { Id = Guid.NewGuid(), Code = "LK", Name = "Sri Lanka" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SD", Name = "Sudan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SR", Name = "Suriname" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SJ", Name = "Svalbard and Jan Mayen" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SZ", Name = "Swaziland" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SE", Name = "Sweden" },
            new Type.Country { Id = Guid.NewGuid(), Code = "CH", Name = "Switzerland" },
            new Type.Country { Id = Guid.NewGuid(), Code = "SY", Name = "Syrian Arab Republic" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TW", Name = "Taiwan, Province of China" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TJ", Name = "Tajikistan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TZ", Name = "Tanzania, United Republic of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TH", Name = "Thailand" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TL", Name = "Timor - Leste" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TG", Name = "Togo" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TK", Name = "Tokelau" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TO", Name = "Tonga" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TT", Name = "Trinidad and Tobago" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TN", Name = "Tunisia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TR", Name = "Turkey" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TM", Name = "Turkmenistan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TC", Name = "Turks and Caicos Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "TV", Name = "Tuvalu" },
            new Type.Country { Id = Guid.NewGuid(), Code = "UG", Name = "Uganda" },
            new Type.Country { Id = Guid.NewGuid(), Code = "UA", Name = "Ukraine" },
            new Type.Country { Id = Guid.NewGuid(), Code = "AE", Name = "United Arab Emirates" },
            new Type.Country { Id = Guid.NewGuid(), Code = "GB", Name = "United Kingdom" },
            new Type.Country { Id = Guid.NewGuid(), Code = "US", Name = "United States" },
            new Type.Country { Id = Guid.NewGuid(), Code = "UM", Name = "United States Minor Outlying Islands" },
            new Type.Country { Id = Guid.NewGuid(), Code = "UY", Name = "Uruguay" },
            new Type.Country { Id = Guid.NewGuid(), Code = "UZ", Name = "Uzbekistan" },
            new Type.Country { Id = Guid.NewGuid(), Code = "VU", Name = "Vanuatu" },
            new Type.Country { Id = Guid.NewGuid(), Code = "VE", Name = "Venezuela, Bolivarian Republic of" },
            new Type.Country { Id = Guid.NewGuid(), Code = "VN", Name = "Viet Nam" },
            new Type.Country { Id = Guid.NewGuid(), Code = "VG", Name = "Virgin Islands, British" },
            new Type.Country { Id = Guid.NewGuid(), Code = "VI", Name = "Virgin Islands, U.S." },
            new Type.Country { Id = Guid.NewGuid(), Code = "WF", Name = "Wallis and Futuna" },
            new Type.Country { Id = Guid.NewGuid(), Code = "EH", Name = "Western Sahara" },
            new Type.Country { Id = Guid.NewGuid(), Code = "YE", Name = "Yemen" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ZM", Name = "Zambia" },
            new Type.Country { Id = Guid.NewGuid(), Code = "ZW", Name = "Zimbabwe" }
        };

        private readonly IBus _bus;

        public Country(IBus bus)
        {
            _bus = bus;
        }

        public async Task<Boolean> Seed()
        {
            var commands = Data.Select(x => new Commands.Create
            {
                CountryId = x.Id,
                Code = x.Code,
                Name = x.Name,
                Timestamp = DateTime.UtcNow.Ticks,
                UserId = User.Data.ElementAt(0).Id
            });
            await commands.WhenAllAsync(x => _bus.Send(x).IsCommand<Command>());

            this.Done = true;
            return this.Done;
        }

        public Boolean Done { get; private set; }
    }
}